<?php

namespace MenuBundle\Entity;

/**
 * MenuTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
