services:
#    menu.example:
#        class: MenuBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  admin.menu:
    class: MenuBundle\Admin\MenuAdmin
    tags:
      - { name:  sonata.admin, manager_type: orm, group: Структура, label: Меню}
    arguments: [null, MenuBundle\Entity\Menu, SonataAdminBundle:CRUD]
     
  admin.menu_type:
    class: MenuBundle\Admin\MenuTypeAdmin
    tags:
      - { name:  sonata.admin, manager_type: orm, group: Структура, label: Меню Тип}
    arguments: [null, MenuBundle\Entity\MenuType, SonataAdminBundle:CRUD]