feedback_create:
    path:     /api/feedback/{blockid}
    defaults: { _controller: "AppBundle:Default:create" }
    requirements: 
        _method: post            
        blockid: '\d+'

page_release:
    path: /release/{slug}
    defaults: { _controller: "AppBundle:Default:release" }

page_artist_up:
    path: /admin/page_artist_up/{page_id}
    defaults:  { _controller: "AppBundle:PageTreeSort:up" }

page_artist_down:
    path: /admin/page_artist_down/{page_id}
    defaults:  { _controller: "AppBundle:PageTreeSort:down" }    

page_slide_up:
    path: /admin/page_slide_up/{page_id}
    defaults:  { _controller: "AppBundle:SlideTreeSort:up" }

page_slide_down:
    path: /admin/page_slide_down/{page_id}
    defaults:  { _controller: "AppBundle:SlideTreeSort:down" }    

chertovskaya:
    path: /chertovskaya/
    defaults: { _controller: "AppBundle:Chertovskaya:default" }

page_level0:
    path:   /
    defaults: { _controller: "AppBundle:Default:level0" }

page_level1:
    path:   /{slug}/
    defaults: { _controller: "AppBundle:Default:level1" }    

page_level2:
    path:   /{slug}/{slug_0}
    defaults: { _controller: "AppBundle:Default:level2" }

page_level3:
    path:   /{slug}/{slug_0}/{slug_1}
    defaults: { _controller: "AppBundle:Default:level3" }
