AppBundle\Entity\Artist:
  type: entity
  table: null
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    path:
      type: string
      length: 255
    title:
      type: string
      length: 255
    content:
      type: text
      nullable: true
    social_fb:
      type: string
      length: 255
      nullable: true
    social_vk:
      type: string
      length: 255
      nullable: true
    social_tw:
      type: string
      length: 255
      nullable: true
    social_ytube:
      type: string
      length: 255
      nullable: true
    social_inst:
      type: string
      length: 255
      nullable: true

  manyToMany:
    slides01:
      targetEntity: Slide
      joinTable:
        name: artist_slides01
        joinColumns:
          artist_id:
            referencedColumnName: id

    routes:
      targetEntity: Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Orm\Route
      cascade: ["persist", "remove"]        

  manyToOne:
    image:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: image
        referencedColumnName: id
    
    poster:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: poster
        referencedColumnName: id

  oneToMany:
    music:
      targetEntity: Music
      mappedBy: artist
    video:
      targetEntity: Video
      mappedBy: artist
