AppBundle\Entity\Artist:
  type: entity
  table: null
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    path:
      type: string
      length: 255
    title:
      type: string
      length: 255