AppBundle\Entity\Artist:
  type: entity
  repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
  table: null
  gedmo:
    tree:
      type: nested
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    path:
      type: string
      length: 255
    title:
      type: string
      length: 255
    content:
      type: text
      nullable: true
    social_fb:
      type: string
      length: 255
      nullable: true
    social_vk:
      type: string
      length: 255
      nullable: true
    social_tw:
      type: string
      length: 255
      nullable: true
    social_ytube:
      type: string
      length: 255
      nullable: true
    social_inst:
      type: string
      length: 255
      nullable: true
    lft:
      type: integer
      gedmo:
        - treeLeft
    rgt:
      type: integer
      gedmo:
        - treeRight
    lvl:
      type: integer
      gedmo:
        - treeLevel

  manyToMany:
    slides01:
      targetEntity: Slide
      joinTable:
        name: artist_slides01
        joinColumns:
          artist_id:
            referencedColumnName: id

    routes:
      targetEntity: Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Orm\Route
      cascade: ["persist", "remove"]        

  manyToOne:
    image:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: image
        referencedColumnName: id
    
    poster:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: poster
        referencedColumnName: id

    poster_sq:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: poster_sq
        referencedColumnName: id

    root:
      targetEntity: Artist
      joinColumn:
        name: tree_root
        referencedColumnName: id
        onDelete: CASCADE
      gedmo:
        - treeRoot
          # identifierMethod: getRoot2

    parent:
      targetEntity: Artist
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: CASCADE
      gedmo:
        - treeParent

  oneToMany:
    music:
      targetEntity: Music
      mappedBy: artist
      orderBy: { 'releasedate': 'DESC' }
    video:
      targetEntity: Video
      mappedBy: artist

    children:
      targetEntity: Artist
      mappedBy: parent
      orderBy:
        lft: ASC