AppBundle\Entity\Feedback:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\FeedbackRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mail:
            type: string
            length: 255
        name:
            type: string
            length: 255
        phone:
            type: string
            length: 255
        who:
            type: string
            length: 255
            nullable: true
        type:
            type: string
            length: 255
        createdAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
