AppBundle\Entity\Feedback:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        field01:
            type: string
            length: 255
            nullable: true
        field02:
            type: string
            length: 255
            nullable: true
        field03:
            type: string
            length: 255
            nullable: true
        field04:
            type: string
            length: 255
            nullable: true
        field05:
            type: string
            length: 255
            nullable: true
        field06:
            type: string
            length: 255
            nullable: true
        field07:
            type: string
            length: 255
            nullable: true
        field08:
            type: string
            length: 255
            nullable: true
        field09:
            type: string
            length: 255
            nullable: true
        field10:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
