AppBundle\Entity\News:
  type: entity
  table: null
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
      nullable: true
    tag:
      type: string
      length: 255
      nullable: true
    link:
      type: string
      length: 255
      nullable: true
    newsdate:
      type: date
      nullable: true
    descr:
      type: string
      length: 255
      nullable: true
    content:
      type: text      
      nullable: true
    public:
      type: boolean      
      nullable: true      

  manyToOne:
    picture:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: picture
        referencedColumnName: id