AppBundle\Entity\Slide:
  type: entity
  repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
  table: null
  gedmo:
    tree:
      type: nested  
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
    slide_title:
      type: string
      length: 255
      nullable: true
    slide_descr:
      type: string
      length: 255
      nullable: true
    button:
      type: string
      length: 255
      nullable: true
    link:
      type: string
      length: 255
      nullable: true
    lft:
      type: integer
      gedmo:
        - treeLeft
    rgt:
      type: integer
      gedmo:
        - treeRight
    lvl:
      type: integer
      gedmo:
        - treeLevel

  manyToOne:
    image:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: image
        referencedColumnName: id

    video:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: video
        referencedColumnName: id
    
    root:
      targetEntity: Slide
      joinColumn:
        name: tree_root
        referencedColumnName: id
        onDelete: CASCADE
      gedmo:
        - treeRoot          

    parent:
      targetEntity: Slide
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: CASCADE
      gedmo:
        - treeParent      

  oneToMany:
    children:
      targetEntity: Slide
      mappedBy: parent
      orderBy:
        lft: ASC